[phases.setup]
nixPkgs = ["python312", "gcc", "stdenv.cc.cc.lib", "zlib"]

[phases.install]
cmds = ["cd python && pip install uv && uv sync"]

[start]
cmd = "cd python && python -m uvicorn src.server.main:socket_app --host 0.0.0.0 --port $PORT"