# Railway configuration for Archon backend services

[build]
builder = "nixpacks"
buildCommand = "cd python && pip install uv && uv sync"

[deploy]
startCommand = "cd python && python -m uvicorn src.server.main:socket_app --host 0.0.0.0 --port $PORT"
numReplicas = 1
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3